### ISSUE TITLE
Doesn't Appear to Work: Module Name/Desc Needs Changing

### ISSUE THREAD

**Issue by shellscape** [dwmkerr/wait-port#14]
~~I hate being vague but I'm not sure how else to describe it. I ran:~~

```console
$ wait-port 8080
```

~~Waited about a minute and it never recognized the port open. I verified the port was open by using:~~

```console
$ netstat -vanp tcp | grep 8080
```

~~For which the output was empty (indicating that 8080 wasn't being used by anything)~~

--

_Update:_ OK, I just realized that this module works in the opposite direction. The verbiage in the description and the module name choice is really what threw me. When a port is _open_ that's generally understood to mean that it's _NOT in use_. The way you're describing this module following that is that it waits for a port to be in use so that a service can be connected to. Given that you're using a module name accompanied by a description that's going to indicate waiting for an open port (in the traditional sense), please do consider updating your description in the README and republishing. As is, it's counter-intuitive.

**Comment by dwmkerr** [comment]
Ah thanks for letting me know @shellscape - I can see how this might be confusing, happy to take a PR on the README if you've got a few mins!

**Comment by dwmkerr** [comment]
I haven't had anyone else raise issues on the syntax, so I will leave it for now, the best would probably be to call it `wait-socket` as a socket can certainly be open and this is actually what is being checked for. Although with more and more features it is starting to become more of a general `wait` utility!
