### ISSUE TITLE
Error: Cannot find module 'wait-port'

### ISSUE THREAD

**Issue by JasoonS** [dwmkerr/wait-port#24]
When I run this via a javascript script I get the following error `Error: Cannot find module 'wait-port'`

I am using node version v8.11.1
and npm version: 6.2.0
My machine is running Ubuntu: 18.04

I installed this package both globally and inside the project I'm working on. (`npm install -g wait-port`, `npm install -s wait-port`)

I ran the code exactly as you use it in your example (https://github.com/dwmkerr/wait-port#api)

Help would be appreciated since this library would make my life much easier :)

**Comment by JasoonS** [comment]
My humble apologies! I installed wait-port in the wrong folder!! (Microservices... joy ;) ) 

Thank you for the great library!

**Comment by dwmkerr** [comment]
No worries @JasoonS glad it's all working!
