### ISSUE TITLE
Error: getaddrinfo ENOTFOUND

### ISSUE THREAD

**Issue by vitramir** [dwmkerr/wait-port#41]
I use this package to wait mongodb deployment inside Kubernetes. Sometimes DNS records do not have time to create, then I receive error "Error: getaddrinfo ENOTFOUND". 

Is it bug or feature?

I think wait-port should also wait while DNS record appears.

**Comment by dwmkerr** [comment]
Would a flag such as:

```
--wait-for-dns
```

Work for this? i.e. opt-in. Otherwise for people who simply type in the wrong address they'll have to wait for timeouts or check the output if there's an error.

WDYT?

**Comment by vitramir** [comment]
I think that my use case with undefined dns record is not usual and the flag "--wait-for-dns" will be enough.

**Comment by dwmkerr** [comment]
Done! The latest version has the `wait-for-dns` flag - if this works for you as expected let me know and I will close the issue.

**Comment by vitramir** [comment]
It works! Awesome! Thank you!

**Comment by dwmkerr** [comment]
Cool, glad it works and the tool as another potential valuable use now!
