### ISSUE TITLE
Newest version of library doesn't work with CentOS7

### ISSUE THREAD

**Issue by saskewindeed** [dwmkerr/wait-port#81]
Hello,

Thank you all for maintaining this project! We find it very useful in our pipelines. 

We saw with the latest release that `wait-port` is no longer working as expected with CentOS7. The command will continue to hang even though the port in question has been opened.  Could someone take a look please? Thanks!

**Comment by anmonteiro** [comment]
I believe this is a problem when using Node.js 18, where it's trying to connect to `::1` rather than `localhost`. Downgrading to Node.js v16 worked.

**Comment by dwmkerr** [comment]
This should be fixed shortly with @danez 's change, just testing against different node versions then will publish, apologies for the delay
