### ISSUE TITLE
Timeout doesn't work correctly

### ISSUE THREAD

**Issue by banool** [dwmkerr/wait-port#83]
See this invocation where I use just a random port with nothing running:
```
$ wait-port -t 5000 http://127.0.0.1:54545
Waiting for 127.0.0.1:54545..................
```

Another invocation, where I assume the timeout is in seconds instead of milliseconds in case that was the issue:
```
$ wait-port -t 5 http://127.0.0.1:54545
Waiting for 127.0.0.1:54545............................
```

You can see by the dots that it has been well over 5 seconds.

Version:
```
$ wait-port --version
0.3.0
```

I'm on MacOS 12.5.

Am I missing something here? This is causing big issues in our CI because this just never times out.

**Comment by dwmkerr** [comment]
Fixed with #85 and released as `0.3.1`
