### ISSUE TITLE
exitcode after timeout is always 0 (after release 0.2.9)

### ISSUE THREAD

**Issue by alexandredevely** [dwmkerr/wait-port#89]
Hello,

The exit code after a time out is always 0, and should be 1.
On this exemple no tcp is listening on port 6082
( on Linux ubuntu 18.04 )

```
$ ./node_modules/.bin/wait-port -t 5 172.17.0.12:6082
Waiting for 172.17.0.12:6082..
Timeout
$ echo $?
0
```

same issue in debug mode.

**Comment by dwmkerr** [comment]
Yes this is fixed in the latest release, please do re-open if the issue persists!

**Comment by alexandredevely** [comment]
@dwmkerr Thank you so much for your response

I will do a re-open because this issue persists, let's dump version information:

If the latest release in 1.0.0, as describe on [npmjs.com](https://www.npmjs.com/package/wait-port).
This exit code is still 0.

Show `nodejs` and `wait-port` version
```
desktop:/tmp/node_modules/wait-port/bin$ node -v
v16.17.0
desktop:/tmp/node_modules/wait-port/bin$ ./wait-port.js -V
1.0.0
```

Show the `$?` exit code value with `wait-port` release `1.0.0`
```
desktop:/tmp/node_modules/wait-port/bin$ ./wait-port.js -t 500 localhost:123 
Waiting for localhost:123...
Timeout
desktop:/tmp/node_modules/wait-port/bin$ echo $?
0
```

**Comment by alexandredevely** [comment]
I can't re-open this issue because you closed yourself, it's a (strange) github's feature...

**Comment by dwmkerr** [comment]
@alexandredevely 😂 sorry about that I didn't know I had such power! Let me set up a test to reproduce the issue and see what is going on, thanks for your patience!

**Comment by dwmkerr** [comment]
Very silly mistake on my part which is fixed now (I really need to unit test the `./bin/wait-port.js` file if possible - the actual internal APIs are all working it's the little wrapper that calls it that had a refactoring error. Very frustrating - sorry for the hassle on this. Fixed in `v1.0.1`

**Comment by alexandredevely** [comment]
Thank you so much, your patch fixes the issue. 
I like your wait-port project, i use it to make sure that a tcp port is listening in abcdesktop.io project.
wait-port is light, and reduce the attack surface than other tools like `netcat`.  

I confirm the exit code is fixed 

```
$./wait-port.js -V
1.0.1
$ ./wait-port.js -t 123 localhost:342
Waiting for localhost:342...
Timeout
$ echo $?
1
```

That's really nice, thank you again for your time.

**Comment by dwmkerr** [comment]
Glad to help!
