### ISSUE TITLE
Error: connect EADDRNOTAVAIL ::1:3003

### ISSUE THREAD

**Issue by avegancafe** [dwmkerr/wait-port#92]
Hello! I'm trying to use this util to wait for a server to start in gitlab CI and am seeing this error message immediately as soon as this command is run, not really sure why. Any ideas as to how this could happen? Thanks in advance for your consideration.

```
$ npx --yes wait-port --wait-for-dns http://:3003/
Waiting for localhost:3003..
Unknown error occurred waiting for http://:3003/: Error: connect EADDRNOTAVAIL ::1:3003 - Local (:::0)
```

Cheers,
Kyle

**Comment by yeusiukou** [comment]
I experienced the same issue. This was fixed in the latest release. Resolved here: https://github.com/dwmkerr/wait-port/issues/89

**Comment by dwmkerr** [comment]
OK thanks for the heads up @yeusiukou ! I'll close this issue but happy to reopen if it is still occurs, thanks all!
